#!/bin/bash

: "${CMAKE_PREFIX_PATH:=""}"
: "${CMAKE_BUILD_TYPE:="RelWithDebInfo"}"
: "${GENERATOR:="Visual Studio 16 2019"}"
: "${MAIN_FOLDER:="$PWD"}"
: "${BUILD_FOLDER:="$MAIN_FOLDER/build"}"

cmake \
-DCMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH" \
-DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE" \
-B$BUILD_FOLDER \
-G"$GENERATOR" -A x64

cmake --build $BUILD_FOLDER --config $CMAKE_BUILD_TYPE